### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by CTrando** [CTrando/UCSD-Planner-Helper#27]
Integrate docker to make it easier to setup the dev environment

**Comment by dmhacker** [comment]
Please see commits:

https://github.com/CTrando/UCSD-Planner-Helper/commit/a3af86f8a8c30403da74011ee431cc0e69ed4e9b
https://github.com/CTrando/UCSD-Planner-Helper/commit/54156fbcf2a39a5c2654ff9274d03b9528ef0a35

I somewhat messed up; I thought the backend/frontend folder structure wasn't merged to master, so I did my initial docker stuff in scratch/issue23, which somewhat polluted the branch. However, I merged all of my changes into scratch/issue27 and can confirm that they are working. See the first commit for details on how the Docker containers are set up. The new environment can be completely set up with two commands:

```
docker-compose build
docker-compose run
```

Bon appetite.

@CTrando @snowme34

**Comment by snowme34** [comment]
@dmhacker @CTrando 

For our `docker-install.sh`, I think we should not run this at the end of script

```bash
docker-compose up
```

After all, it's just a script for installment, right?

**Comment by dmhacker** [comment]
@CTrando 

This issue is really old and has been resolved a long time ago. Can we close this issue & branch?
