### ISSUE TITLE
Possibly duplicated api_classes http requests

### ISSUE THREAD

**Issue by snowme34** [CTrando/UCSD-Planner-Helper#55]
When the user types a department, there is a chance that the browser will send duplicated `api_calsses` requests. It happens more frequently when the user did not type everything in uppercase.

![image](https://user-images.githubusercontent.com/13925662/50527608-43cb0580-0a9e-11e9-8760-87e169a4c969.png)

Steps to reproduce:
1. Open https://sdschedule.com/
2. Click the blank for `Department`
3. Type a department name and click the autocomplete
4. Two requests will be sent:
  * One when the user finishes typing
  * Another one when the user clicks the autocomplete

Don't know if this would be a concern. 

But it might be better to have a local cache for the data fetched from server. It would be faster if next time user selects the same department, the browser can use the local cache directly.

**Comment by CTrando** [comment]
So there is already a local cache. I'm not sure how you were able to get the frontend code to send fetch requests using mixed case departments. But I have pushed something that now more strictly enforces the uppercasing of departments - even added some tests. If you are interested in JS, check it out.

**Comment by CTrando** [comment]
Fixed in the bug fixes packaged in #40.
